package View;

import java.awt.Dimension;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

import Controller.TratadorAcusa;
import Controller.TratadorArmaAcusada;
import Controller.TratadorComodoAcusado;
import Controller.TratadorPalpita;
import Controller.TratadorSuspeitoAcusado;
import Model.API;

public class JanelaPalpita extends JFrame {
	public JanelaPalpita(JanelaDeJogo janela){
		super("Palpita");
		setResizable(false);
		JRadioButton p1=new JRadioButton(API.getNome(0)); 
		JRadioButton p2=new JRadioButton(API.getNome(1));
		JRadioButton p3=new JRadioButton(API.getNome(2));    
		JRadioButton p4=new JRadioButton(API.getNome(3));
		JRadioButton p5=new JRadioButton(API.getNome(4));    
		JRadioButton p6=new JRadioButton(API.getNome(5));
		p1.setBounds(75,50,200,30);
		p2.setBounds(75,75,200,30);
		p3.setBounds(75,100,200,30);
		p4.setBounds(75,125,200,30);
		p5.setBounds(75,150,200,30);  
		p6.setBounds(75,175,200,30);
		JRadioButton a1=new JRadioButton(API.getArma(0));    
		JRadioButton a2=new JRadioButton(API.getArma(1));
		JRadioButton a3=new JRadioButton(API.getArma(2));    
		JRadioButton a4=new JRadioButton(API.getArma(3));
		JRadioButton a5=new JRadioButton(API.getArma(4));    
		JRadioButton a6=new JRadioButton(API.getArma(5));
		a1.setBounds(275,50,200,30);
		a2.setBounds(275,75,200,30);
		a3.setBounds(275,100,200,30);
		a4.setBounds(275,125,200,30);
		a5.setBounds(275,150,200,30);  
		a6.setBounds(275,175,200,30);  
		JRadioButton c1=new JRadioButton(API.getComodo(0));    
		JRadioButton c2=new JRadioButton(API.getComodo(1));
		JRadioButton c3=new JRadioButton(API.getComodo(2));    
		JRadioButton c4=new JRadioButton(API.getComodo(3));
		JRadioButton c5=new JRadioButton(API.getComodo(4));    
		JRadioButton c6=new JRadioButton(API.getComodo(5));
		JRadioButton c7=new JRadioButton(API.getComodo(6));    
		JRadioButton c8=new JRadioButton(API.getComodo(7));
		JRadioButton c9=new JRadioButton(API.getComodo(8));    
		c1.setBounds(475,50,200,30);
		c2.setBounds(475,75,200,30);
		c3.setBounds(475,100,200,30);
		c4.setBounds(475,125,200,30);
		c5.setBounds(475,150,200,30);  
		c6.setBounds(475,175,200,30);
		c7.setBounds(475,200,200,30);  
		c8.setBounds(475,225,200,30); 
		c9.setBounds(475,250,200,30);   
		ButtonGroup personagens=new ButtonGroup();
		personagens.add(p1);
		personagens.add(p2);
		personagens.add(p3);
		personagens.add(p4);
		personagens.add(p5);
		personagens.add(p6);
		add(p1);
		add(p2);
		add(p3);
		add(p4);
		add(p5);
		add(p6);
		ButtonGroup armas=new ButtonGroup(); 
		armas.add(a1);
		armas.add(a2);
		armas.add(a3);
		armas.add(a4);
		armas.add(a5);
		armas.add(a6);
		add(a1);
		add(a2);
		add(a3);
		add(a4);
		add(a5);
		add(a6);
		p1.addActionListener(new TratadorSuspeitoAcusado(this));
		p1.doClick();
		p2.addActionListener(new TratadorSuspeitoAcusado(this));
		p3.addActionListener(new TratadorSuspeitoAcusado(this));
		p4.addActionListener(new TratadorSuspeitoAcusado(this));
		p5.addActionListener(new TratadorSuspeitoAcusado(this));
		p6.addActionListener(new TratadorSuspeitoAcusado(this));
		a1.addActionListener(new TratadorArmaAcusada(this));
		a1.doClick();
		a2.addActionListener(new TratadorArmaAcusada(this));
		a3.addActionListener(new TratadorArmaAcusada(this));
		a4.addActionListener(new TratadorArmaAcusada(this));
		a5.addActionListener(new TratadorArmaAcusada(this));
		a6.addActionListener(new TratadorArmaAcusada(this));
		JButton palpita = new JButton("Palpitar");
		palpita.setBounds(175,225,120,30);
		palpita.addActionListener(new TratadorPalpita(this, janela));
		add(palpita);
		personagens.setSelected(p1.getModel(), true);
		armas.setSelected(a1.getModel(), true);
		JPanel newp = new JPanel();
		newp.setLayout(null);
		newp.setPreferredSize(new Dimension(10,10));
		add (newp);
		setLocationRelativeTo(null);
		setBounds(0,0,700,400);
		setVisible(true);
	}

}